name: StaffTeam
main: callum\staffteam
version: 1.35
api: [3.0.0]
author: callum

commands:
    staffteam:
        description: "view staff team"
        usage: "/staffteam <list|info|help>"
        permission: staffteam
        
permissions:
    staffteam:
        description: "/staffteam"
        default: true
        
